### PR TITLE
Refresh and correct recipe

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Getting clobber error with lark-parser, I thinking a rebuild and rerender might address the issues.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
@mlin @tarcisioe
Could you please review and merge. 
Thank you and regards.

**Comment by tarcisioe** [comment]
@rxm7706 my only question: why is the `--no-build-isolation` needed in the build script.

**Comment by rxm7706** [comment]
> @rxm7706 my only question: why is the `--no-build-isolation` needed in the build script?

Hi @tarcisioe - It's not required, but has been the default for a while - with Grayskull for conda recipes. 
  - https://github.com/conda/grayskull/blob/main/grayskull/strategy/pypi.py#L66
  - https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-no-build-isolation
 Thank you

**Pull request merged**
